# Setup
title: 450のブログ
url: https://getpoole.com
paginate: 3
baseurl: ""
permalink: pretty

domain: 450.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://450.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /450blog     # place folder name if the site is served in a subfolder

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: 450
  url: https://twitter.com/450hosigata
  email:

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Blog
    url: /archive

  - title: About
    url: /about
